### ISSUE TITLE
Plugins (namely rpm signing)

### ISSUE THREAD

**Issue by abutcher** [abutcher/juicer#22]
Still need to move this over from old-juicer.

**Comment by abutcher** [comment]
Spit balling here but what if we loaded arbitrary plugins that could be applied to a type of item in an environment either before pushing (pre-hook) or after pushing (post-hook) ... @vbatts asked for something like this ages ago https://github.com/juicer/juicer/issues/120).

Totally made up config that might not be the best way to do this.
```
[devel]
plugins:
    pre:
       rpm:
          - SomePlugin.SomeAction
    post:
       rpm:
          - AnotherPlugin.SomeAction
```
